version: '3'
services:
  db:
    image: postgres
    networks:
      - backend
    volumes: 
      - storage:/var/lib/postgresql/data
  web:
    build: .
    networks:
      - frontend
      - backend
    depends_on:
      - db
    ports:  
      - "8000:8080"
    environment:
      - DATABASE_URL=${PROTOCOL}://${DB_USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}
volumes: 
  storage:
networks:
  frontend:
  backend:
